apiVersion: v2
name: my-hub
description: A Helm chart for deploying the ArgoCD Example JupyterHub

type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: jupyterhub
    version: 3.3.7
    repository: https://hub.jupyter.org/helm-chart/